Feature/affiliation fix
AtlasOfLivingAustralia/ala-bootstrap3 pull request #31
Opened 2023-10-05 04:54 UTC by yasima-csiro

- Fix #30
- Update to new common ui
- Refactor close button in the affiliation popup to OK button.

2023-10-10 06:30 UTC, sbearcsiro requested changes
Looks good, just change the close button to a link instead of onclick

2023-10-10 06:30 UTC, sbearcsiro commented on grails-app/views/layouts/_main.gsp
> +                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="window.location.href = '${u.createLink(baseProperty:'userdetails.url', pathsProperty: 'userdetails.prof
this should just be a link, not use JS

2023-10-11 03:55 UTC, yasima-csiro commented on grails-app/views/layouts/_main.gsp
> +                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="window.location.href = '${u.createLink(baseProperty:'userdetails.url', pathsProperty: 'userdetails.prof
Fixed.

2023-10-13 05:36 UTC, sbearcsiro approved these changes

2023-10-15 21:59 UTC, merged